### ISSUE TITLE
Getting 401 in gradle build

### ISSUE THREAD

**Issue by tushar09** [liu-wanshun/platform_frameworks_libs_systemui#1]
When I trying to run this project I am getting:
Could not GET 'https://maven.pkg.github.com/liu-wanshun/platform_frameworks_base/com/github/liu-wanshun/launcherlib-systemui-shared/13-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized error. Any idea why is that?

**Comment by liu-wanshun** [comment]
you mean LauncherC?
you should config `gpr.user` and `gpr.key` in  `gradle.properties`

see https://github.com/liu-wanshun/LauncherC/blob/c13/settings.gradle#L18C1-L24C103

**Comment by tushar09** [comment]
Thank you.
